name: CI
on: [push, pull_request]
 
jobs:
  build:
      name: Build and Lint
      runs-on: ubuntu-latest
      env:
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        
      steps:
        - name: Check out code
          uses: actions/checkout@v3
 
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.32.2
 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'pnpm'
 
        - name: Install dependencies
          run: pnpm install
 
        - name: Build
          run: pnpm build
 
        - name: Lint
          run: pnpm lint